
#variables
@base_url = http://localhost/api/v1
@bearer = Bearer
@access_token = {{refreshToken.response.body.access_token}} 
@refresh_token = {{login.response.body.refresh_token}}
@otp_token = {{send_otp.response.body.access_token}}
@confirm_token = {{register.response.body.access_token}}


# @name test
GET {{base_url}}
x-lang: fr
### 

# @name get_docs
GET http://localhost/docs
###

# @name register
POST {{base_url}}/auth/register
Content-Type: application/json

{
    "firstname": "ABALO",
    "lastname": "Koffi",
    "email": "bkgdevs03@gmail.com",
    "password": "password",
    "phone": "+22892942605"
}
### 

# Confirm account
# @name confirm_account
POST {{base_url}}/auth/confirm-account
Content-Type: application/json
Authorization: {{bearer}} {{confirm_token}}

{
    "otp": "101034"
}
###

# @name verify_otp
# @prompt otp Enter OTP
POST {{base_url}}/auth/verify
Content-Type: application/json

{
    "otp": "{{otp}}"
}
### 

# @name login
POST {{base_url}}/auth/login
Content-Type: application/json

{
    "username": "root",
    "password": "fnyky1rj"
}
###

# @name get_profile
GET {{base_url}}/auth/profile HTTP/1.1
Content-Type: application/json
Accept: application/json
Authorization: {{bearer}} eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2ZTg0OTZlZjFjOWFlODhiYmUxNjU5NCIsImxhc3RuYW1lIjoiQXJvdW5hIiwiZmlyc3RuYW1lIjoiQU1BRE9VIiwidXNlcm5hbWUiOiJrMGQzLnMwbjFrQGdtYWlsLmNvbSIsInBob25lIjoyMjg5Mjk0MjYwNCwiZW1haWwiOiJrMGQzLnMwbjFrQGdtYWlsLmNvbSIsImdlbmRlciI6IlUiLCJyb2xlIjoidXNlciIsImRlZmF1bHRVc2VybmFtZSI6ZmFsc2UsImF1dGhNZXRob2RzIjpbXSwicGFzc3dvcmQiOiIkMmIkMTAkdDZFL2hHOVN1NlJ5ZDUucXlaNU9kZXhzYU9UOVVab1VCV0YuRGJtNmlhYXJhaTlEN05URDIiLCJpc0FjdGl2ZSI6dHJ1ZSwiY29tcGxldGVkIjpmYWxzZSwiaW50ZXJlc3RzIjpbXSwiZGVsZXRlZEF0IjpudWxsLCJjb25maXJtZWRBdCI6IjIwMjQtMDktMTZUMTU6MDY6NTUuNTQxWiIsInJlZmVycmFsQ29kZSI6IkswRHo0aWM3cThwIiwicmVmZXJyZWRCeSI6bnVsbCwiY3JlYXRlZEF0IjoiMjAyNC0wOS0xNlQxNTowNjoyMi45OTNaIiwidXBkYXRlZEF0IjoiMjAyNC0wOS0xNlQxNTowNjoyMi45OTNaIiwiaWF0IjoxNzI2NDk5MjE1LCJleHAiOjE3MjY1MDI4MTV9.7fA41LA83vJO-gov6nbBnQUJFWcF7tphYN8qaOQuqOE
###


# @name refreshToken
Post {{base_url}}/auth/refresh
Content-Type: application/json
Accept: application/json

{
    "refresh_token": "{{refresh_token}}"
}
###

# @name logout
Post {{base_url}}/auth/logout
Content-Type: application/json
Accept: application/json
Authorization: {{bearer}} {{access_token}}
###

# @name update_profile
PUT {{base_url}}/auth/profile
Content-Type: application/json
Accept: application/json
Authorization: {{bearer}} {{access_token}}

{
    "firstname": "John",
    "lastname": "Doe",
}
###

# @name update_email
PUT {{base_url}}/auth/email
Content-Type: application/json
Accept: application/json
Authorization: {{bearer}} {{access_token}}

{
    "email": ""
}
###

# @name update_avatar
PUT {{base_url}}/auth/avatar
Accept: application/json
Authorization: {{bearer}} {{access_token}}

{
    "avatar": "avatar.jpg"
}

# @name update_password
PUT {{base_url}}/auth/password
Content-Type: application/json
Accept: application/json
Authorization: {{bearer}} {{access_token}}

{
    "old_password": "password",
    "new_password": "password123",
}

# @name forgot_password
POST {{base_url}}/auth/forgot-password
Content-Type: application/json

{
    "email": "johndoe4@gmail.com"
}
###

# @name change_password
PUT {{base_url}}/auth/change-password
Content-Type: application/json
Accept: application/json
Authorization: {{bearer}} {{access_token}}

{
    "old_password": "password",
    "new_password": "password123",
}
###

# @name send_otp
POST {{base_url}}/auth/verify-phone
Content-Type: application/json

{
    "phone": "+22871255635"
}
###

# @name verify_otp
POST {{base_url}}/auth/verify-otp
Content-Type: application/json
Authorization: {{bearer}} {{otp_token}}

{
    "otp": "669003",
    "device": {
        "id": "skdfsjdfhkw23232",
        "platform": "android",
        "version": "10",
        "model": "Samsung Galaxy S10",
        "token": "dklsfksdjfljflasjdl"
    }
}
###

# @name complete_profile
POST {{base_url}}/auth/complete-profile
Content-Type: application/json
Authorization: {{bearer}} eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2Zjk3ZjcyMDcwNWMxYjg0OTkwMmYwOCIsInVzZXJuYW1lIjoiKzIyODcxMjU1NjM1OTE1NiIsInBob25lIjoyMjg3MTI1NTYzNSwiZ2VuZGVyIjoiVSIsInJvbGUiOiJ1c2VyIiwiZGVmYXVsdFVzZXJuYW1lIjp0cnVlLCJhdXRoTWV0aG9kcyI6WyJwaG9uZSJdLCJpc0FjdGl2ZSI6dHJ1ZSwiY29tcGxldGVkIjpmYWxzZSwiaW50ZXJlc3RzIjpbXSwiZGVsZXRlZEF0IjpudWxsLCJjb25maXJtZWRBdCI6bnVsbCwicmVmZXJyYWxDb2RlIjpudWxsLCJyZWZlcnJlZEJ5IjpudWxsLCJjcmVhdGVkQXQiOiIyMDI0LTA5LTI5VDE2OjI1OjIyLjY2NloiLCJ1cGRhdGVkQXQiOiIyMDI0LTA5LTI5VDE2OjI1OjIyLjY2NloiLCJpYXQiOjE3Mjc2MjcxMjIsImV4cCI6MTcyNzYzMDcyMn0.kR7xa8u-ByKGF6fryxyEAqCK6UpsCI0C8eVx28nv6Xc

{
    "firstname": "John",
    "lastname": "Doe",
    "username": "johndoe17",
    "email": "aroamadou@gmail.com",
    "birthdate": "30/01/2010",
    "address": "Jl. Jend. Sudirman No. 1",
    "interests": ["football", "music", "dance"]
}
###

# @name Check email unicity
POST {{base_url}}/auth/check-credential
Content-Type: application/json

{
    "email": "aroamadou@gmail.com"
}

###

# @name Check username unicity
POST {{base_url}}/auth/check-credential
Content-Type: application/json

{
    "username": "johndoe17"
}

###

# @name Check phone unicity
POST {{base_url}}/auth/check-credential
Content-Type: application/json

{
    "phone": "+22892942601"
}
###
