name: tz
services:
# App 
  gateway:
    container_name: tz-gateway
    build:
      context: ../..
      dockerfile: ./devops/dev/Dockerfile
      target: development
    env_file:
      - .env
    volumes:
      - ../../node_modules:/usr/src/app/node_modules
      - ../../src:/usr/src/app/src
      - ../../public:/usr/src/app/public
      # - /usr/src/app/node_modules
    ports:
      - "3000"
    environment:
      NODE_ENV: development
    command: npm run start:dev

# MongoDB with username and password
  mongo-db:
    container_name: tz-mongo-db
    image: mongo
    # restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      # MONGO_INITDB_ROOT_DATABASE: db
    volumes:
      - ./data/mongo:/data/db

# Redis Db with username and password
  redis-db:
    container_name: tz-redis-db
    image: redis
    # restart: always
    ports:
      - "6379:6379"
    command: 'redis-server --requirepass root'
    volumes:
      - ./data/redis:/data

# Proxy
  nginx-proxy:
    container_name: tz-nginx-proxy
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - gateway
      - mongo-db
      - redis-db
